name: Delivery docker image

on:
  push:
    branches: [ "main", "INT" ]
    tags:
      - v*.*.**

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Identify Version
      id: get_version
      uses: battila7/get-version-action@v2
  
    - name: Docker images latest
      run: |
          docker-compose build    
          docker-compose push

    - name: Docker images version
      env:
          VERSION: ${{ steps.get_version.outputs.version }}
      run: |
          docker-compose build
          docker-compose push

    - name: Docker images version mayor
      if: ${{ steps.get_version.outputs.is-semver }}
      env:
          VERSION: v${{ steps.get_version.outputs.mayor }}
      run: |
          docker-compose build
          docker-compose push

    - name: Docker images version mayor.minor
      if: ${{ steps.get_version.outputs.is-semver }}
      env:
          VERSION: v${{ steps.get_version.outputs.mayor }}.${{ steps.get_version.outputs.minor }}
      run: |
          docker-compose build
          docker-compose push

    - name: Docker images version mayor.minor.patch
      if: ${{ steps.get_version.outputs.is-semver }}
      env:
          VERSION: v${{ steps.get_version.outputs.mayor }}.${{ steps.get_version.outputs.minor }}.${{ steps.get_version.outputs.patch }}
      run: |
          docker-compose build
          docker-compose push