name: Delivery docker image

on:
  push:
    branches: [ "main", "INT" ]
    tags:
      - v*.*.**

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Identify Version
      id: get_version
      uses: battila7/get-version-action@v2
  
    - name: Version identified
      run: |
        echo "version: ${{ steps.get_version.outputs.version}}"
        echo "is-semver: ${{ steps.get_version.outputs.is-semver }}"
        echo "major: ${{ steps.get_version.outputs.major }}"
        echo "minor: ${{ steps.get_version.outputs.minor }}"
        echo "patch: ${{ steps.get_version.outputs.patch }}"
        echo "prerelease: ${{ steps.get_version.outputs.prerelease }}"
        echo "build: ${{ steps.get_version.outputs.build }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME_PRIV }}
        password: ${{ secrets.DOCKERHUB_TOKEN_PRIV }}

    - name: Docker images latest
      run: |
          docker-compose build    
          docker-compose push

    - name: Docker images version
      env:
          VERSION: ${{ steps.get_version.outputs.version }}
      run: |
          docker-compose build
          docker-compose push

    - name: Docker images version major
      if: ${{ steps.get_version.outputs.is-semver }}
      env:
          VERSION: v${{ steps.get_version.outputs.major }}
      run: |
          docker-compose build
          docker-compose push

    - name: Docker images version major.minor
      if: ${{ steps.get_version.outputs.is-semver }}
      env:
          VERSION: v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}
      run: |
          docker-compose build
          docker-compose push

    - name: Docker images version major.minor.patch
      if: ${{ steps.get_version.outputs.is-semver }}
      env:
          VERSION: v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}.${{ steps.get_version.outputs.patch }}
      run: |
          docker-compose build
          docker-compose push